### ISSUE TITLE
尊敬的张老师，您好，我想请教一下install.sh文件只能在Linux系统运行吗？如果在Windows10系统下运行，应该如何运行?

### ISSUE THREAD

**Issue by senyaguojin** [Bobholamovic/ESCNet#3]
尊敬的张老师，您好，我想请教一下install.sh文件只能在Linux系统运行吗？如果在Windows10系统下运行，应该如何运行?

**Comment by Bobholamovic** [comment]
你好！（我是张老师的学生）
如果环境配好的话，这份代码理论上应该可以在Windows10系统下运行，但由于仓库没有提供win系统的批处理脚本，所以可能需要手动在`lib`目录的每个子目录中运行` python setup.py install`指令安装相应的模块。在安装完所有模块后，`demo.py`脚本应该就能顺利运行了。
